### ISSUE TITLE
Plz  change the name of the repo to "lCARE-BTU-HU"

### ISSUE THREAD

**Issue by lborke** [QuantLet/lCARE-BTU-HUB#1]
I think
"lCARE-BTU-HU-"
was a typo

**Comment by xuxiu** [comment]
how to change it? I change it locally, seems not work

**Comment by andrijamihoci** [comment]
Dear Lukas,

no, there is no typo.

Andrija Mihoci

Zitat von Lukas Borke notifications@github.com:

> I think
> "lCARE-BTU-HU-"
> was a typo
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/QuantLet/lCARE-BTU-HU-/issues/1

## 

Brandenburgische Technische Universität Cottbus-Senftenberg
Lehrstuhl für Ökonometrie und Wirtschaftsstatistik

Andrija Mihoci
Lehrgebäude 10, Raum 439a
Erich-Weinert-Straße 1
03046 Cottbus

fon     +49 (0) 355 69 38 20

mail   Andrija.Mihoci@b-tu.de
Web    b-tu.de/fg-oekonometrie

Brandenburg University of Technology
Chair of Econometrics and Business Statistics

**Comment by lborke** [comment]
Then I need a written confirmation of WH that
**lCARE-BTU-HU-**
is correct.
Otherwise this repo will not be involved into the final validation and the D3 Visu.
Thanks.

**Comment by andrijamihoci** [comment]
That's fine with me. Thanks,

Andrija Mihoci

Quoting Lukas Borke notifications@github.com:

> Then I need a written confirmation of WH that
> **lCARE-BTU-HU-**
> is correct.
> Otherwise this repo will no be involved into the final validation  
> and the D3 Visu.
> Thanks.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/QuantLet/lCARE-BTU-HU-/issues/1#issuecomment-157007324

## 

Brandenburgische Technische Universität Cottbus-Senftenberg
Lehrstuhl für Ökonometrie und Wirtschaftsstatistik

Andrija Mihoci
Lehrgebäude 10, Raum 439a
Erich-Weinert-Straße 1
03046 Cottbus

fon     +49 (0) 355 69 38 20

mail   Andrija.Mihoci@b-tu.de
Web    b-tu.de/fg-oekonometrie

Brandenburg University of Technology
Chair of Econometrics and Business Statistics

**Comment by lborke** [comment]
I need the written confirmation of WH.

Don't you read my text?

**Comment by andrijamihoci** [comment]
Dear Lukas,

that's fine with me. If you need it, then it's fine with me (I don't  
have anything against).

Best regards,

Andrija Mihoci

Quoting Lukas Borke notifications@github.com:

> I need the written confirmation of WH.
> 
> Don't you read my text?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/QuantLet/lCARE-BTU-HU-/issues/1#issuecomment-157015631

## 

Brandenburgische Technische Universität Cottbus-Senftenberg
Lehrstuhl für Ökonometrie und Wirtschaftsstatistik

Andrija Mihoci
Lehrgebäude 10, Raum 439a
Erich-Weinert-Straße 1
03046 Cottbus

fon     +49 (0) 355 69 38 20

mail   Andrija.Mihoci@b-tu.de
Web    b-tu.de/fg-oekonometrie

Brandenburg University of Technology
Chair of Econometrics and Business Statistics

**Comment by lborke** [comment]
You are kidding!!!

No cooperation, no final validation!!!

You are wasting my time!

**Comment by andrijamihoci** [comment]
Quoting Lukas Borke notifications@github.com:

> You are kidding!!!
> 
> No cooperation, no final validation!!!
> 
> You are wasting my time!
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/QuantLet/lCARE-BTU-HU-/issues/1#issuecomment-157016351

## 

Brandenburgische Technische Universität Cottbus-Senftenberg
Lehrstuhl für Ökonometrie und Wirtschaftsstatistik

Andrija Mihoci
Lehrgebäude 10, Raum 439a
Erich-Weinert-Straße 1
03046 Cottbus

fon     +49 (0) 355 69 38 20

mail   Andrija.Mihoci@b-tu.de
Web    b-tu.de/fg-oekonometrie

Brandenburg University of Technology
Chair of Econometrics and Business Statistics

**Comment by lborke** [comment]
https://github.com/QuantLet/Styleguide-and-Validation-procedure

No further comments.
